<a href="https://colab.research.google.com/github/sanchit-Thakur/BDA-EXPERIMENT/blob/main/ML_Lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([5, 4, 3, 2, 1])

print("Array 1:", arr1)
print("Array 2:", arr2)

Array 1: [1 2 3 4 5]
Array 2: [5 4 3 2 1]

In [ ]:
exp_value_arr1 = np.mean(arr1)
exp_value_arr2 = np.mean(arr2)

print(f"Expected Value (Mean) of Array 1: {exp_value_arr1}")
print(f"Expected Value (Mean) of Array 2: {exp_value_arr2}")

Expected Value (Mean) of Array 1: 3.0
Expected Value (Mean) of Array 2: 3.0

### Mean

In [ ]:
mean_array1 = np.mean(arr1)
mean_array2 = np.mean(arr2)

print(f"Mean of Array 1: {mean_array1}")
print(f"Mean of Array 2: {mean_array2}")

Mean of Array 1: 3.0
Mean of Array 2: 3.0

### Standard Deviation

In [ ]:
std_dev_arr1 = np.std(arr1)
std_dev_arr2 = np.std(arr2)

print(f"S.D of Array 1: {std_dev_arr1}")
print(f"S.D of Array 2: {std_dev_arr2}")

S.D of Array 1: 1.4142135623730951
S.D of Array 2: 1.4142135623730951

### Variance

In [ ]:
var_arr1 = np.var(arr1)
var_arr2 = np.var(arr2)

print(f"Var of Array 1: {var_arr1}")
print(f"Var of Array 2: {var_arr2}")

Var of Array 1: 2.0
Var of Array 2: 2.0

### Covariance and Covariance Matrix

In [ ]:
data = np.vstack((arr1, arr2))
cov_matrix = np.cov(data)

print("Covariance Matrix:")
print(cov_matrix)

cov_arr1_arr2 = cov_matrix[0, 1]
print(f"\nCovariance between Array 1 and Array 2: {cov_arr1_arr2}")

Covariance Matrix:
[[ 2.5 -2.5]
 [-2.5  2.5]]

Covariance between Array 1 and Array 2: -2.5

experiment:- 3

In [ ]:
import pandas as pd
import numpy as np
import sklearn as sklearn
data = pd.read_csv("/content/MLexp.3.csv")
print(data)

           Name Class  Roll No
0  Aarav Sharma   X-A    101.0
1   Priya Patel   NaN    102.0
2   Rohan Gupta   X-B      NaN
3  Ananya Singh   X-A    104.0
4    Vikram Rao   NaN      NaN
5   Sneha Verma   X-C    106.0
6   Rahul Mehta   NaN    107.0
7    Divya Nair   X-B    108.0
8    Amit Kumar   X-A      NaN
9   Pooja Joshi   NaN    110.0

In [ ]:
data.head(6)

           Name Class  Roll No
0  Aarav Sharma   X-A    101.0
1   Priya Patel   NaN    102.0
2   Rohan Gupta   X-B      NaN
3  Ananya Singh   X-A    104.0
4    Vikram Rao   NaN      NaN
5   Sneha Verma   X-C    106.0

In [ ]:
data.tail(3)

          Name Class  Roll No
7   Divya Nair   X-B    108.0
8   Amit Kumar   X-A      NaN
9  Pooja Joshi   NaN    110.0

In [ ]:
data.isnull()

    Name  Class  Roll No
0  False  False    False
1  False   True    False
2  False  False     True
3  False  False    False
4  False   True     True
5  False  False    False
6  False   True    False
7  False  False    False
8  False  False     True
9  False   True    False

In [ ]:
data.shape

(10, 3)

In [ ]:
data.describe

<bound method NDFrame.describe of            Name Class  Roll No
0  Aarav Sharma   X-A    101.0
1   Priya Patel   NaN    102.0
2   Rohan Gupta   X-B      NaN
3  Ananya Singh   X-A    104.0
4    Vikram Rao   NaN      NaN
5   Sneha Verma   X-C    106.0
6   Rahul Mehta   NaN    107.0
7    Divya Nair   X-B    108.0
8    Amit Kumar   X-A      NaN
9   Pooja Joshi   NaN    110.0>

In [ ]:
data.info

<bound method DataFrame.info of            Name Class  Roll No
0  Aarav Sharma   X-A    101.0
1   Priya Patel   NaN    102.0
2   Rohan Gupta   X-B      NaN
3  Ananya Singh   X-A    104.0
4    Vikram Rao   NaN      NaN
5   Sneha Verma   X-C    106.0
6   Rahul Mehta   NaN    107.0
7    Divya Nair   X-B    108.0
8    Amit Kumar   X-A      NaN
9   Pooja Joshi   NaN    110.0>

In [ ]:
data.fillna(0)

           Name Class  Roll No
0  Aarav Sharma   X-A    101.0
1   Priya Patel     0    102.0
2   Rohan Gupta   X-B      0.0
3  Ananya Singh   X-A    104.0
4    Vikram Rao     0      0.0
5   Sneha Verma   X-C    106.0
6   Rahul Mehta     0    107.0
7    Divya Nair   X-B    108.0
8    Amit Kumar   X-A      0.0
9   Pooja Joshi     0    110.0

In [ ]:
data.fillna(method = 'ffill')

/tmp/ipykernel_2704/3794184318.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method = 'ffill')

           Name Class  Roll No
0  Aarav Sharma   X-A    101.0
1   Priya Patel   X-A    102.0
2   Rohan Gupta   X-B    102.0
3  Ananya Singh   X-A    104.0
4    Vikram Rao   X-A    104.0
5   Sneha Verma   X-C    106.0
6   Rahul Mehta   X-C    107.0
7    Divya Nair   X-B    108.0
8    Amit Kumar   X-A    108.0
9   Pooja Joshi   X-A    110.0

In [ ]:
data.fillna(method = 'bfill')

/tmp/ipykernel_2704/3058535179.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method = 'bfill')

           Name Class  Roll No
0  Aarav Sharma   X-A    101.0
1   Priya Patel   X-B    102.0
2   Rohan Gupta   X-B    104.0
3  Ananya Singh   X-A    104.0
4    Vikram Rao   X-C    106.0
5   Sneha Verma   X-C    106.0
6   Rahul Mehta   X-B    107.0
7    Divya Nair   X-B    108.0
8    Amit Kumar   X-A    110.0
9   Pooja Joshi   NaN    110.0

In [ ]:
# Import necessary libraries
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report

# 1. Load the dataset
iris = load_iris()
X = pd.DataFrame(iris.data, columns=iris.feature_names) # Features
y = iris.target # Target variable

print("Dataset Loaded Successfully.")
print(f"Total samples: {X.shape[0]}, Total features: {X.shape[1]}\n")

# 2. Split the data into Training and Testing sets (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 3. Initialize the Machine Learning Model
# Using Decision Tree for this classification task
model = DecisionTreeClassifier(random_state=42)

# 4. Train the model
model.fit(X_train, y_train)
print("Model Training Completed.\n")

# 5. Make predictions on the test data
y_pred = model.predict(X_test)

# 6. Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Model Accuracy: {accuracy * 100:.2f}%\n")

print("Classification Report:")
print(classification_report(y_test, y_pred, target_names=iris.target_names))

Dataset Loaded Successfully.
Total samples: 150, Total features: 4

Model Training Completed.

Model Accuracy: 100.00%

Classification Report:
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

In [ ]:
# Import necessary libraries
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier

# 1. Create the appropriate dataset (Classic Play Tennis Dataset)
data = {
    'Outlook': ['Sunny', 'Sunny', 'Overcast', 'Rain', 'Rain', 'Rain', 'Overcast', 'Sunny', 'Sunny', 'Rain', 'Sunny', 'Overcast', 'Overcast', 'Rain'],
    'Temperature': ['Hot', 'Hot', 'Hot', 'Mild', 'Cool', 'Cool', 'Cool', 'Mild', 'Cool', 'Mild', 'Mild', 'Mild', 'Hot', 'Mild'],
    'Humidity': ['High', 'High', 'High', 'High', 'Normal', 'Normal', 'Normal', 'High', 'Normal', 'Normal', 'Normal', 'High', 'Normal', 'High'],
    'Wind': ['Weak', 'Strong', 'Weak', 'Weak', 'Weak', 'Strong', 'Strong', 'Weak', 'Weak', 'Weak', 'Strong', 'Strong', 'Weak', 'Strong'],
    'PlayTennis': ['No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No']
}

df = pd.DataFrame(data)
print("Original Dataset Head:\n", df.head(), "\n")

# 2. Preprocess the data
# Scikit-learn algorithms require numerical input, so we use LabelEncoder
encoders = {}
for column in df.columns:
    le = LabelEncoder()
    df[column + '_n'] = le.fit_transform(df[column])
    encoders[column] = le

# Separate features (X) and target (y)
X = df[['Outlook_n', 'Temperature_n', 'Humidity_n', 'Wind_n']]
y = df['PlayTennis_n']

# 3. Initialize and train the Decision Tree using ID3 logic
# Setting criterion='entropy' forces the model to use Information Gain (the core of ID3)
model = DecisionTreeClassifier(criterion='entropy', random_state=42)
model.fit(X, y)
print("ID3 Decision Tree Model Trained Successfully.\n")

# 4. Classify a new sample
# Defining a new unseen sample: Outlook=Rain, Temperature=Cool, Humidity=Normal, Wind=Strong
new_sample = pd.DataFrame({
    'Outlook': ['Rain'],
    'Temperature': ['Cool'],
    'Humidity': ['Normal'],
    'Wind': ['Strong']
})

# Encode the new sample using the previously fitted encoders
new_sample_encoded = pd.DataFrame({
    'Outlook_n': encoders['Outlook'].transform(new_sample['Outlook']),
    'Temperature_n': encoders['Temperature'].transform(new_sample['Temperature']),
    'Humidity_n': encoders['Humidity'].transform(new_sample['Humidity']),
    'Wind_n': encoders['Wind'].transform(new_sample['Wind'])
})

# Make the prediction
prediction_encoded = model.predict(new_sample_encoded)

# Decode the prediction back to 'Yes' or 'No'
prediction_label = encoders['PlayTennis'].inverse_transform(prediction_encoded)

print("--- Classification of New Sample ---")
print("New Sample:")
print(new_sample.iloc[0].to_dict())
print(f"Predicted Class (PlayTennis): {prediction_label[0]}")

Original Dataset Head:
     Outlook Temperature Humidity    Wind PlayTennis
0     Sunny         Hot     High    Weak         No
1     Sunny         Hot     High  Strong         No
2  Overcast         Hot     High    Weak        Yes
3      Rain        Mild     High    Weak        Yes
4      Rain        Cool   Normal    Weak        Yes

ID3 Decision Tree Model Trained Successfully.

--- Classification of New Sample ---
New Sample:
{'Outlook': 'Rain', 'Temperature': 'Cool', 'Humidity': 'Normal', 'Wind': 'Strong'}
Predicted Class (PlayTennis): No

In [ ]:
# Import necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans, AgglomerativeClustering
import scipy.cluster.hierarchy as sch

# 1. Load and Preprocess the Dataset
iris = load_iris()
X = iris.data

# Standardization is crucial for PCA and distance-based clustering algorithms
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
print("Data Standardized successfully.\n")

# ==========================================
# 2. Principal Component Analysis (PCA)
# ==========================================
# Reduce from 4 dimensions to 2 dimensions for easier visualization
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)

print("--- PCA Summary ---")
print(f"Original shape: {X_scaled.shape}")
print(f"Reduced shape: {X_pca.shape}")
print(f"Explained Variance Ratio: {pca.explained_variance_ratio_}\n")

# ==========================================
# 3. K-Means Clustering
# ==========================================
# Applying K-Means on the PCA-reduced data
kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)
kmeans_labels = kmeans.fit_predict(X_pca)

print("--- K-Means Clustering ---")
print("K-Means Cluster Centers:\n", kmeans.cluster_centers_)
print("K-Means Labels assigned successfully.\n")

# ==========================================
# 4. Hierarchical Clustering
# ==========================================
# Applying Agglomerative Hierarchical Clustering
hierarchical = AgglomerativeClustering(n_clusters=3, metric='euclidean', linkage='ward')
hierarchical_labels = hierarchical.fit_predict(X_pca)

print("--- Hierarchical Clustering ---")
print("Hierarchical Labels assigned successfully.\n")

# ==========================================
# 5. Visualizing the Results
# ==========================================
plt.figure(figsize=(14, 5))

# Plot 1: K-Means Results
plt.subplot(1, 2, 1)
plt.scatter(X_pca[:, 0], X_pca[:, 1], c=kmeans_labels, cmap='viridis', edgecolor='k', s=50)
plt.scatter(kmeans.cluster_centers_[:, 0], kmeans.cluster_centers_[:, 1],
            s=200, c='red', marker='X', label='Centroids')
plt.title("K-Means Clustering (PCA-Reduced Data)")
plt.xlabel("Principal Component 1")
plt.ylabel("Principal Component 2")
plt.legend()

# Plot 2: Hierarchical Clustering Results
plt.subplot(1, 2, 2)
plt.scatter(X_pca[:, 0], X_pca[:, 1], c=hierarchical_labels, cmap='plasma', edgecolor='k', s=50)
plt.title("Hierarchical Clustering (PCA-Reduced Data)")
plt.xlabel("Principal Component 1")
plt.ylabel("Principal Component 2")

plt.tight_layout()
plt.show()

# Optional: Generate a Dendrogram to visualize the hierarchical building process
plt.figure(figsize=(10, 5))
plt.title("Hierarchical Clustering Dendrogram")
dendrogram = sch.dendrogram(sch.linkage(X_pca, method='ward'))
plt.xlabel("Sample Index")
plt.ylabel("Euclidean Distance")
plt.show()